esg-node's createdb call error handling
It turns out that psql does have different return values for different
categories of errors. error status 1 means that there was an internal
sql database error... such as creating a database that already
exisits. Error status >1 indicate some external to psql error,
i.e. connection error, credential failure, etc...  So now just testing
for error codes >1.

diff --git a/bin/esg-node b/bin/esg-node
--- a/bin/esg-node
+++ b/bin/esg-node
@@ -1428,7 +1428,7 @@ configure_postgress() {
     echo "Creating esg node database: ${node_db_name}"
     echo "${postgress_install_dir}/bin/createdb ${node_db_name}"
     ${postgress_install_dir}/bin/createdb ${node_db_name}
-    #[ $? != 0 ] && echo " ERROR: Could not create esg node database: ${node_db_name}" && return 0
+    (( $? > 1 )) && echo " ERROR: Could not create esg node database: ${node_db_name}" && return 0
         
     #TODO... Make the above call idempotent...
     #NOTE: (zoiks) Need to be able to tell the difference between a
