esg-update: verbiage change... no biggie

diff --git a/bin/esg-update b/bin/esg-update
--- a/bin/esg-update
+++ b/bin/esg-update
@@ -123,7 +123,7 @@ usage() {
 if id_check 
 then
     self_verify >& /dev/null
-    (( $? > 0 )) && printf "WARNING: $0 could not be verified!! \n(This file, ${0}, has been tampered with)\n\n" && exit 1
+    (( $? > 0 )) && printf "WARNING: $0 could not be verified!! \n(This file, ${0}, may have been tampered with or there is a newer version posted at the distribution server.\nPlease re-fetch this script.)\n\n" && exit 1
     echo "checking on updates for $@"
     if (( ($# < 3) && ($# > 0) )); then
 	for type in "$@"
