esg-node: better self_verify with prompt

diff --git a/bin/esg-node b/bin/esg-node
--- a/bin/esg-node
+++ b/bin/esg-node
@@ -1993,11 +1993,31 @@ dedup() {
     return 0
 }
 
-self_verify() {
+#"private" function
+_verify() {
     echo "diff <(md5sum ${0} | tr -s " " | cut -d " " -f 1) <(curl ${esg_dist_url}/esg-node/${0##*/}.md5 | tr -s " " | cut -d " " -f 1) >& /dev/null "
     diff <(md5sum ${0} | tr -s " " | cut -d " " -f 1) <(curl ${1}/esg-node/${0##*/}.md5 | tr -s " " | cut -d " " -f 1) >& /dev/null
-    [ $? != 0 ] && echo " WARNING: Could not verify myself!" && return 3
+    [ $? != 0 ] && return 3
     echo "[VERIFIED]"
+    return 0
+}
+
+self_verify() {
+    _verify 'http://rainbow.llnl.gov/dist' >& /dev/null 
+    if (( $? == 3 )); then 
+	printf "WARNING: $0 could not be verified!! \n(This file, ${0}, may have been tampered with or there is a newer version posted at the distribution server.\nPlease re-fetch [esg-update] this script.)\n\n"
+	local do_anyway
+	read -t $((3*60)) -p "Do you wish to continue anyway? [y/N]: " do_anyway
+	if [ "$do_anyway" = "Y" ] || [ "$do_anyway" = "y" ]; then
+	    echo 
+	    return 0
+	else
+	    echo
+	    exit 1
+	fi
+    else
+	return 0
+    fi
     return 0
 }
 
@@ -2350,8 +2370,7 @@ main() {
 #trap stop_tomcat INT TERM
 #trap - INT TERM
 
-self_verify 'http://rainbow.llnl.gov/dist' >& /dev/null 
-(( $? > 0 )) && printf "WARNING: $0 could not be verified!! \n(This file, ${0}, may have been tampered with or there is a newer version posted at the distribution server.\nPlease re-fetch [esg-update] this script.)\n\n" && exit 1
+self_verify
 
 echo "start time: `date`" >> ${logfile}
 main $@
