esg-node script: updated thredds to 4.1 and creating thredds default root and replica directories at the end of TDS install
Now we also have the thredds.war file as part of our distribution
repository

diff --git a/bin/esg-node b/bin/esg-node
--- a/bin/esg-node
+++ b/bin/esg-node
@@ -158,8 +158,8 @@ init() {
     tomcat_dist_url=http://download.filehat.com/apache/tomcat/tomcat-6/v6.0.20/bin/apache-tomcat-6.0.20.tar.gz
     tomcat_pid_file=/var/run/tomcat-jsvc.pid
     utils_url=http://rainbow.llnl.gov/dist/utils
-    thredds_dist_url=ftp://ftp.unidata.ucar.edu/pub/thredds/3.17/thredds.war
-    thredds_esg_dist_url=http://rainbow.llnl.gov/dist/thredds/3.17/thredds.war
+    thredds_dist_url=ftp://ftp.unidata.ucar.edu/pub/thredds/4.1/thredds.war
+    thredds_esg_dist_url=http://rainbow.llnl.gov/dist/thredds/4.1/thredds.war
     #NOTE: This root dir should match a root set in the thredds setup 
     thredds_root_dir=/esg/data
     thredds_replica_dir=/esg/data.replica
@@ -707,6 +707,8 @@ test_esgcet() {
     esgcet_testdir=${thredds_root_dir}/test
     mkdir -p ${esgcet_testdir}
     [ $? != 0 ] && checked_done 1
+    mkdir -p ${thredds_replica_dir}
+    [ $? != 0 ] && checked_done 1
 
     echo "esgcet test directory: [${esgcet_testdir}]"
     local fetch_file
@@ -1077,8 +1079,8 @@ setup_tds() {
 	wget -O ${thredds_dist_file} ${thredds_dist_url}
 	if [ $? != 0 ]; then
 	    echo " ERROR: Could not download ${thredds_dist_url}, fetching the copy at PCMDI (LLNL)..."
-	    wget -O ${thredds_dist_file} ${thredds_esg_dist_url}
-	    [ $? != 0 ] && echo " ERROR: Could not download ${thredds_esg_dist_url} either" && popd && checked_done 1
+	    checked_get ${thredds_dist_file} ${thredds_esg_dist_url}
+	    (( $? > 1 )) && echo " ERROR: Could not download ${thredds_esg_dist_url} either" && popd && checked_done 1
 	fi
     fi
     
@@ -1153,7 +1155,7 @@ setup_tds() {
 
     mkdir -p $tomcat_install_dir/conf/Catalina/localhost
     fetch_file=thredds.xml
-    checked_get $tomcat_install_dir/conf/Catalina/localhost/${fetch_file} ${esg_dist_url}/externals/bootstrap/${fetch_file}
+    checked_get $tomcat_install_dir/conf/Catalina/localhost/${fetch_file} ${esg_dist_url}/externals/bootstrap/tomcat-${fetch_file}
     (( $? > 1 )) && echo " ERROR: Problem pulling down ${fetch_file} from esg distribution" && popd && checked_done 1
 
     
@@ -1172,7 +1174,7 @@ setup_tds() {
     chown tomcat.tomcat $tomcat_install_dir/webapps/thredds/WEB-INF/lib/${fetch_file}
 
     fetch_file=web.xml
-    checked_get $tomcat_install_dir/webapps/thredds/WEB-INF/${fetch_file} ${esg_dist_url}/externals/bootstrap/thredds.${fetch_file}
+    checked_get $tomcat_install_dir/webapps/thredds/WEB-INF/${fetch_file} ${esg_dist_url}/externals/bootstrap/thredds/thredds.${fetch_file}
     (( $? > 1 )) && popd && checked_done 1
     chown tomcat.tomcat $tomcat_install_dir/webapps/thredds/WEB-INF/${fetch_file}
 
@@ -1242,6 +1244,10 @@ setup_tds() {
 
     popd >& /dev/null
     echo
+    mkdir -p ${thredds_root_dir}
+    [ $? != 0 ] && echo " Error: could not create ${thredds_root_dir}" && checked_done 1
+    mkdir -p ${thredds_replica_dir}
+    [ $? != 0 ] && echo " Error: could not create ${thredds_replica_dir}" && checked_done 1
     echo
     write_tds_env
     checked_done 0
