Switches work... writing config type to {esg_root_dir}/config/config_type
So, start must be the LAST arg read therefore --type data &| index
must be before it or they won't get read!  The --type args set the
$sel var that is filtered throug bit vectors that tell the script
which functions to run to achieve a particular node configuration
type.  As of this commit there are only two data and index (for data
node and index node respectively).

When a successful start is done it writes out the $sel (--type)
numeral value to file.  Subsequently start may be the only argument to
esg-node because it will read the needed $sel value from the written
{esg_root_dir}/config/config_type.

I have put this bit vector filtering also as a part of the installation.

NOTE: It is only in the case of start stop status restart where the
--type flag and arg(s) must precede.

Also....
Set default values for question on "Do you want to continue wth FOO
installation..."  to [Y/n], yes.  This has been modified where ever a
check_*_version call can be made.

:-\ I think this should really be nearing a close on the scripting!
-gavin

diff --git a/bin/esg-node b/bin/esg-node
--- a/bin/esg-node
+++ b/bin/esg-node
@@ -609,10 +609,12 @@ setup_ant() {
     echo "*******************************"
     echo
 
+    local default="Y"
     local dosetup
     if [ -x ${ant_install_dir}/bin/ant ]; then 
         echo "Detected an existing ant installation..."
         read -p "Do you want to continue with Ant installation and setup? [y/N] " dosetup
+        [ -z ${dosetup} ] && dosetup=${default}
         if [ "${dosetup}" != "Y" ] && [ "${dosetup}" != "y" ]; then
             echo "Skipping Ant installation and setup - will assume ant is setup properly"
             return 0
@@ -706,10 +708,12 @@ setup_postgress() {
     echo "*******************************"
     echo
 
+    local default="Y"
     local dosetup
     if [ -x ${postgress_install_dir}/bin/psql ]; then 
         echo "Detected an existing postgress installation..."
-        read -p "Do you want to continue with Postgres installation and setup? [y/N] " dosetup
+        read -p "Do you want to continue with Postgres installation and setup? [Y/n] " dosetup
+        [ -z ${dosetup} ] && dosetup=${default}
         if [ "${dosetup}" != "Y" ] && [ "${dosetup}" != "y" ]; then
             echo "Skipping postgres installation and setup - will assume postgres is setup properly"
             return 0
@@ -1060,10 +1064,12 @@ setup_esgcet() {
     echo "*******************************"
     echo
     
+    local default="Y"
     local dosetup
     if [ -e ${HOME}/.esgcet/esg.ini ]; then 
         echo "Detected an existing esgcet installation..."
-        read -p "Do you want to continue with esgcet installation and setup? [y/N] " dosetup
+        read -p "Do you want to continue with esgcet installation and setup? [Y/n] " dosetup
+        [ -z ${dosetup} ] && dosetup=${default}
         if [ "${dosetup}" != "Y" ] && [ "${dosetup}" != "y" ]; then
             echo "Skipping esgcet installation and setup - will assume esgcet is setup properly"
             return 0
@@ -3275,7 +3281,7 @@ check_module_version() {
     local module_name=$1
     local target_version=$2
     
-    local current_version=$(${cdat_home}/bin/python -c "import ${module_name}; print ${module_name}.__version__" >& /dev/null)
+    local current_version=$(${cdat_home}/bin/python -c "import ${module_name}; print ${module_name}.__version__" 2> /dev/null)
     [ $? != 0 ] && echo " WARNING:(2) Could not detect version of ${module_name}" && return 2
     [ -z "${current_version}" ] && echo " WARNING:(1) Could not detect version of ${module_name}" && return 3
 
@@ -3531,14 +3537,19 @@ show_svc_list() {
 #Starts the esg node
 start() {
     init
-    echo "starting services... "
-    local sel=${1:-${DNODE_BIT}}
+    echo "starting services... ($1)"
+    local sel=${1}
+    ((sel == 0)) && printf "ERROR: No node type selected! \n Consult usage with --help flag... look for the \"--type\" flag must come BEFORE \"start\" arg\n\n" && exit 1
+
     start_postgress
     start_tomcat
     (( ! no_globus )) && source ${scripts_dir}/esg-globus >& /dev/null && \
         start_globus_services datanode ${gridftp_config_args} 
     [ $((sel & INDEX_BIT)) != 0 ] && source ${scripts_dir}/esg-search >& /dev/null && start_search_services
     show_svc_list
+
+    echo "${sel}" > ${esg_root_dir}/config/config_type
+    ((DEBUG)) && cat ${esg_root_dir}/config/config_type
     echo
 }
 
@@ -3723,7 +3734,11 @@ INDEX_BIT=8
 WRITE_ENV_BIT=16
 
 main() {
-    let sel=0
+
+    local last_config_type=$(cat ${esg_root_dir}/config/config_type 2> /dev/null)
+    (($DEBUG)) && echo "last_config_type = ${last_config_type}"
+
+    let sel=${last_config_type:-0}
     while [ -n "$1" ]; do
     #echo "arg ${i} = $1"
         local unshift=0
@@ -3745,7 +3760,7 @@ main() {
                 until [ $(echo $1 | egrep '^\s*--') ] || [ -z "$1" ] || [ "$1" = "stop" ] || [ "$1" = "start" ] || [ "$1" = "status" ] || [ "$1" = "restart" ]; do
                     tvalue=$(echo "$1" | tr 'A-Z' 'a-z')
                     #turn on the proper bit when string is detected
-                    (($DEBUG)) && echo "node type selected is: $1"
+                    echo "node type selected is: $1"
                     [ "data"  = "${tvalue}" ] && (( (sel & DNODE_BIT) == 0 )) && ((sel+=DNODE_BIT))
                     [ "index" = "${tvalue}" ] && (( (sel & INDEX_BIT) == 0 )) && ((sel+=INDEX_BIT))
                     shift
@@ -3755,8 +3770,8 @@ main() {
             start | --start)
                 check_prerequisites
                 [ $? != 0 ] && echo && exit 1
-                (($DEBUG)) && echo "START SERVICES"
-                start
+                (($DEBUG)) && echo "START SERVICES (${sel})"
+                start $sel
                 exit 0
                 ;;
             stop | --stop)
