check_webapp_version function
Now checks for webapp version.  Looks into the webapps MANIFEST.MF
file for "Version:" attribute. Uses this to check.

diff --git a/bin/esg-node b/bin/esg-node
--- a/bin/esg-node
+++ b/bin/esg-node
@@ -1654,6 +1654,11 @@ test_tomcat() {
 # In update mode it will always pull down latest after archiving old
 #
 setup_node() {
+    echo -n "Checking for node manager ${node_version}"
+    check_webapp_version "esg-node" ${node_version}
+    local ret=$?
+    ((ret == 0)) && (( ! force_install )) && echo " [OK]" && return 0
+
     echo
     echo "*******************************"
     echo "Setting up The ESG Node Manager..."
@@ -1662,17 +1667,20 @@ setup_node() {
 
     local upgrade=${1:-0}
 
+    local default="Y"
     local dosetup
     if [ -d ${node_app_home} ]; then 
         echo "Detected an existing node manager installation..."
-        read -p "Do you want to continue with node manager installation and setup? [y/N] " dosetup
+        read -p "Do you want to continue with node manager installation and setup? [Y/n] " dosetup
+        [ -z "${dosetup}" ] && dosetup=${default}
         if [ "${dosetup}" != "Y" ] && [ "${dosetup}" != "y" ]; then
             echo "Skipping node manager installation and setup - will assume it's setup properly"
             return 0
         fi
         
-        local dobackup="N"
-        read -p "Do you want to make a back up of the existing distribution?? [y/N] " dobackup
+        local dobackup="Y"
+        read -p "Do you want to make a back up of the existing distribution?? [Y/n] " dobackup
+        [ -z "${dobackup}" ] && dobackup=${default}
         if [ "${dobackup}" = "Y" ] || [ "${dobackup}" = "y" ]; then
             echo "Creating a backup archive of this web application $node_app_home"
             backup ${node_app_home}
@@ -2765,7 +2773,7 @@ install_signed_certificate() {
     [ -e ${keystore_file} ] && echo "(making backup copy of keystore)" && cp -v ${keystore_file} ${keystore_file}.bak
 
     #--------------
-    keytool -v -list -keystore /usr/local/tomcat/conf/keystore-tomcat -storepass changeit | egrep -i '^Alias[ ]+name:[ ]+root$'
+    keytool -v -list -keystore ${tomcat_install_dir}/conf/keystore-tomcat -storepass changeit | egrep -i '^Alias[ ]+name:[ ]+root$'
     if [ $? == 0 ]; then
         keytool -delete -alias root -keystore ${keystore_file} -storepass ${store_password}
         [ $? != 0 ] && echo " ERROR: problem deleting root key from keystore!" && return 1
@@ -3284,6 +3292,24 @@ check_module_version() {
     local current_version=$(${cdat_home}/bin/python -c "import ${module_name}; print ${module_name}.__version__" 2> /dev/null)
     [ $? != 0 ] && echo " WARNING:(2) Could not detect version of ${module_name}" && return 2
     [ -z "${current_version}" ] && echo " WARNING:(1) Could not detect version of ${module_name}" && return 3
+
+    (($DEBUG)) && echo " calling helper, check_version_helper ${current_version} >= ${target_version}"
+    check_version_helper "${current_version}" ">=" "${target_version}" # note: bug found (needed to quote the operation ">=")
+    local ret=$?
+    (($DEBUG)) && echo " The return value from the call to helper function check_version_ is $ret"
+    [ $ret == 0 ] && return 0
+
+    printf "\nSorry, the detected version of $1 [${current_version}] is older than required minimum version [$2] \n"
+    return 1
+}
+
+check_webapp_version() {
+    local webapp_name=$1
+    local target_version=$2
+    
+    local current_version=$(sed -n '/^Version:[ ]*\(.*\)/p' ${tomcat_install_dir}/webapps/${webapp_name}/META-INF/MANIFEST.MF | awk '{print $2}' | xargs)
+    [ $? != 0 ] && echo " WARNING:(2) Could not detect version of ${webapp_name}" && return 2
+    [ -z "${current_version}" ] && echo " WARNING:(1) Could not detect version of ${webapp_name}" && return 3
 
     (($DEBUG)) && echo " calling helper, check_version_helper ${current_version} >= ${target_version}"
     check_version_helper "${current_version}" ">=" "${target_version}" # note: bug found (needed to quote the operation ">=")
