esg-node: Now will install GIT if not there and Check_version improved to work for both java and git, etc....

diff --git a/bin/esg-node b/bin/esg-node
--- a/bin/esg-node
+++ b/bin/esg-node
@@ -90,8 +90,10 @@ init() {
     esgcet_version=${esgcet_version:-"2.3"}
     node_version=${node_version:-".0.0.2"}
     java_version=${java_version:-"1.6.0._20"}
+    git_version=${git_version:="1.7.1"}
 
     workdir=${workdir:-~/workbench/esg}
+    git_install_dir=${GIT_HOME:-${install_prefix}/git}
     postgress_install_dir=${PGHOME:-${install_prefix}/pgsql}
     postgress_user=${PGUSER:-dbsuper}
     pg_sys_acct_passwd=${pg_sys_acct_passwd:=changeme}
@@ -148,6 +150,8 @@ init() {
     num_backups_to_keep=${num_backups_to_keep:-7}
     java_dist_url=${esg_dist_url}/java/${java_version}/jdk${java_version}.tar.gz
     ant_dist_url=http://www.trieuvan.com/apache/ant/binaries/apache-ant-1.8.0-bin.tar.gz
+    git_workdir=${workdir}../git
+    git_dist_url=http://kernel.org/pub/software/scm/git/git-1.7.1.tar.gz
     postgress_workdir=${workdir}/../postgress
     postgress_jar=postgresql-8.3-603.jdbc3.jar
     postgress_driver=org.postgresql.Driver
@@ -209,8 +213,8 @@ check_prerequisites() {
     [ $? != 0 ] && echo "[FAIL]" && return 1
     echo "[OK]"
 
-    echo -n "Checking for subversion... "
-    svn --help >& /dev/null
+    echo -n "Checking for GIT... "
+    check_version git ${git_version}
     [ $? != 0 ] && echo "[FAIL]" && return 1
     echo "[OK]"
 
@@ -232,6 +236,92 @@ check_prerequisites() {
     return 0
 }
 
+#####
+# GIT
+#####
+setup_git() {
+    echo
+    echo "*******************************"
+    echo "Setting up GIT (dvcs)..."
+    echo "*******************************"
+    echo
+
+    local dosetup
+    if [ -x ${git_install_dir}/bin/git ]; then 
+	echo "Detected an existing GIT installation..."
+	read -p "Do you want to continue with GIT installation and setup? [y/N] " dosetup
+	if [ "${dosetup}" != "Y" ] && [ "${dosetup}" != "y" ]; then
+	    echo "Skipping GIT installation and setup - will assume GIT is setup properly"
+	    return 0
+	fi
+	echo
+    fi
+
+    mkdir -p $git_workdir
+    [ $? != 0 ] && checked_done 1
+    chmod a+rw $git_workdir
+    pushd $git_workdir >& /dev/null
+
+    local git_dist_file=${git_dist_url##*/}
+    #strip off .tar.gz at the end, i.e. last 7 chars, to get untarred dir name
+    local git_dist_dir=$(echo ${git_dist_file} | awk '{print substr($1,1,length($1)-7)}')
+        
+    #There is this pesky case of having a zero sized dist file... WTF!?
+    if [ -e ${git_dist_file} ]; then
+        ls -l ${git_dist_file}
+	#NOTE: I know there must be a cleaner way to get this, maybe stat?
+        local size=$(ls -l | grep ${git_dist_file} | tr -s " " | cut -d " " -f 5)
+        (( size == 0 )) && rm -v ${git_dist_file}
+    fi
+
+    #Check to see if we have postgres distribution directory
+    if [ ! -e ${git_dist_dir} ]; then
+	echo "Don't see GIT distribution dir ${git_dist_dir}"
+	if [ ! -e ${git_dist_file} ]; then
+	    echo "Don't see GIT distribution file ${git_dist_file} either"
+	    echo "Downloading GIT from ${git_dist_url}"
+	    wget -O ${git_dist_file} ${git_dist_url}
+	    [ $? != 0 ] && echo " ERROR: Could not download GIT:${git_dist_file}" && popd && checked_done 1
+	    tar xvzf ${postgress_dist_file}
+	    [ $? != 0 ] && echo " ERROR: Could not extract GIT: ${git_dist_file}" && popd && checked_done 1
+	fi
+    fi
+
+    #If you don't see the directory but see the tar.gz distribution
+    #then expand it and go from there....
+    if [ -e ${git_dist_file} ] && [ ! -e ${git_dist_dir} ]; then
+	tar xvzf ${git_dist_file}
+    fi
+
+    pushd ${git_dist_dir}
+    echo "./configure --prefix=${git_install_dir}"
+    if ./configure --prefix=${git_install_dir} \
+	&& gmake all \
+	&& gmake install 
+	then
+	echo "Successfully Configured and Built GIT in: ${git_install_dir}"
+	#this is the "test"
+	${git_install_dir}/bin/git --version
+	[ $? != 0 ] && 	echo" ERROR: Could NOT successfully build GIT!!" && popd >& /dev/null && checked_done 1
+    else
+	echo" ERROR: Could NOT successfully build GIT!!"
+	popd >& /dev/null
+	checked_done 1
+    fi
+
+    popd >& /dev/null
+    popd >& /dev/null
+
+    write_git_env
+    checked_done 0
+}
+
+write_git_env() {
+    ((show_summary_latch++))
+    echo "export GIT_HOME=${git_install_dir}" >> ${envfile}
+    dedup ${envfile}
+    return 0
+}
 
 #####
 # Java
@@ -294,6 +384,8 @@ setup_java() {
 	[ $? != 0 ] && \
 	    echo " ERROR*: Could not create sym link ${java_install_dir%/*}/${java_dist_dir} -> ${java_install_dir}" && popd && checked_done 1
     fi
+
+    popd >& /dev/null
 
     ${java_install_dir}/bin/java -version
     [ $? != 0 ] && echo "ERROR cannot run ${java_install_dir}/bin/java" && checked_done 1
@@ -1872,15 +1964,18 @@ check_tomcat_process() {
 }
 
 #-----
-#(A quick and dirty function for checking version [of java])
+#(A quick and dirty function for checking version)
 #-----
 check_version() {
+    [ -z $2 ] && return 0
     ((DEBUG)) && echo $2
-    local target_version=$(echo $2 | perl -ne '/(\d+.\d+.*\d*_*\d*).*/, print "$1 "' | tr -d "." | tr -d "_" | tr -d " ")
+    local target_version=$(echo $2 | perl -ne '/(\d+.*\d*.*\d*[_.]*\d*).*/, print "$1 "' | tr -d "." | tr -d "_" | tr -d " ")
     ((DEBUG)) && echo "target_version = [$target_version]"
-    $1 -version >& /dev/null
+    $1 -version >& /tmp/f || $1 --version >& /tmp/f
     [ $? != 0 ] && echo " ERROR: Problem with $1 command, please check command" && return 2
-    line=($($1 -version 2>&1 | perl -ne '/(\d+.\d+.\d+_\d*).*/, print "$1 "' | tr -d "." | tr -d "_"))
+    line=($(cat /tmp/f 2>&1 | perl -ne '/(\d+.*\d*.*\d*[_.]*\d*).*/, print "$1 "' | tr -d "." | tr -d "_" | tr -d " "))
+
+    rm /tmp/f >& /dev/null
 
     #-----
     #If you are reading this... I know this looks a bit hokey...
