esg-node:coppied basic thredds testing call into thredds install function directly.  Always performs this minimal test at the end of install

diff --git a/bin/esg-node b/bin/esg-node
--- a/bin/esg-node
+++ b/bin/esg-node
@@ -934,14 +934,14 @@ write_cdat_env() {
 
 write_cdat_install_log() {
     echo "$(date ${date_format}) cdat=${cdat_version} ${cdat_home}" >> ${install_logfile}
-
+    
     #Parse the cdat installation config.log file and entries to the install log
     if [ -e ${workdir}/cdat/config.log ]; then
 	awk '/building/ {print "'"$(date ${date_format})"' cdat:"$2"="$NF" <unknown>"}' ${workdir}/cdat/config.log >> ${install_logfile}
     else
 	echo " WARNING: Could not find cdat config.log file [${workdir}/cdat/config.log] installation log entries could not be generated!"
     fi
-
+    
     dedup ${install_logfile}
     return 0
 }
@@ -1765,6 +1765,12 @@ setup_tds() {
     mkdir -p ${thredds_replica_dir}
     [ $? != 0 ] && echo " Error: could not create ${thredds_replica_dir}" && checked_done 1
     echo
+
+    sleep 3
+    echo "curl http://${node_host_ip_address}/thredds"
+    curl http://${node_host_ip_address}/thredds
+    [ $? != 0 ] && echo "[FAILED]" && echo " ERROR: Not able to contact thredds page on this server" && checked_done 1
+    
     write_tds_env
     write_tds_install_log
     checked_done 0
@@ -1791,6 +1797,7 @@ test_tds() {
     [ $? != 0 ] && checked_done 1
     pushd ${workdir} >& /dev/null
 
+    start_tomcat
     start_postgress
 
     echo "$cdat_home/bin/esgpublish --use-existing pcmdi.${esg_root_id}.test.mytest --noscan --thredds"
