Tring to get to a good place... but not...
This is what I get when I try to do a "--test-pub"

GSS Minor Status Error Chain:
globus_gss_assist: Error during context initialization
globus_gsi_gssapi: Unable to verify remote side's credentials
globus_gsi_gssapi: Unable to verify remote side's credentials:
Couldn't verify the remote certificate
OpenSSL Error: s3_pkt.c:1053: in library: SSL routines, function
SSL3_READ_BYTES: sslv3 alert bad certificate SSL alert number 42

Don't know what the issue is. Something with Globus.

diff --git a/bin/esg-node b/bin/esg-node
--- a/bin/esg-node
+++ b/bin/esg-node
@@ -94,13 +94,27 @@ install_logfile=${install_logfile:-"/etc/esg.install_log"}
 init() {
     [ -e "${envfile}" ] && source ${envfile} && ((VERBOSE)) && printf "sourcing environment from: ${envfile} \n"
 
-    #internal data-node code versions
+    #--------------------------------
+    # Internal data-node code versions and supporting external libraries
+    #--------------------------------
     cdat_version=${cdat_version:-"eb8b668"}
     esgcet_version=${esgcet_version:-"2.7.3"}
     esgcet_python_version=${esgcet_python_version:-"2.6"}
     node_version=${node_version:-"0.9.0"}
+
+    #see esg-orp project:
+    esg_orp_version=${orp_version:-"1.0.1"}
+
+    #see esgf-security project:
+    esgf_security_version=${esg_saml_version:-"1.0.2"}
+    opensaml_version=${opensaml_version:-"2.3.2"}
+    openws_version=${openws_version:-"1.3.1"}
+    xmltooling_version=${xmltooling_version:-"1.2.2"}
+    xsgroup_role_version=${xsgroup_role_version:-"1.0.0"}
     
-    #external programs' versions
+    #--------------------------------
+    # External programs' versions
+    #--------------------------------
     curl_version=${curl_version:="7.20.1"}
     git_version=${git_version:="1.7.3"}
     java_version=${java_version:-"1.6.0_20"}
@@ -109,6 +123,9 @@ init() {
     tomcat_version=${tomcat_version:-"6.0.29"}
     tds_version=${tds_version:-"4.2"}
 
+    #--------------------------------
+    # Script vars (~external)
+    #--------------------------------
     curl_install_dir=${CURL_HOME:-${install_prefix}/curl}
     git_install_dir=${GIT_HOME:-${install_prefix}/git}
     postgress_install_dir=${PGHOME:-${install_prefix}/pgsql}
@@ -167,7 +184,7 @@ init() {
     export LDFLAGS="-L$CURL_HOME/lib"
     
     #--------------
-    #ID Setting
+    # ID Setting
     #--------------
     #Yes, I could make this more cleaver and not call id twice but use
     #a single sed expression with two capture groups and then assign
@@ -184,7 +201,7 @@ init() {
     ((VERBOSE)) && echo "${installer_uid}:${installer_gid}:${installer_home}"
 
     #--------------
-    #Script vars (internal)
+    # Script vars (internal)
     #--------------
     esg_backup_dir=${esg_backup_dir:-"${esg_root_dir}/backups"}
     esg_config_dir=${esg_config_dir:-"${esg_root_dir}/config"}
@@ -2324,7 +2341,7 @@ setup_globus() {
 write_globus_env() {
     ((show_summary_latch++))
     echo "export GLOBUS_LOCATION=$GLOBUS_LOCATION" >> ${envfile}
-    echo "export X509_CERT_DIR=\${HOME}/.globus/certificates-esg" >>  ${envfile}
+    echo "export X509_CERT_DIR=$X509_CERT_DIR" >>  ${envfile}
     echo "export gridftp_config_args=$gridftp_config_args" >> ${envfile}
     dedup ${envfile} && source ${envfile}
     return 0
@@ -3745,9 +3762,11 @@ check_webapp_version() {
     local webapp_name=$1
     local target_version=$2
 
+    [ ! -d "${tomcat_install}/webapps/${webapp_name}" ] && echo "Web Application \"${webapp_name}\" is not present or cannot be detected!" && return 2
+
     local current_version=$(sed -n '/^Version:[ ]*\(.*\)/p' ${tomcat_install_dir}/webapps/${webapp_name}/META-INF/MANIFEST.MF | awk '{print $2}' | xargs 2> /dev/null)
-    [ $? != 0 ] && echo " WARNING:(2) Could not detect version of ${webapp_name}" && return 2
-    [ -z "${current_version}" ] && echo " WARNING:(1) Could not detect version of ${webapp_name}" && return 3
+    [ $? != 0 ] && echo " WARNING:(2) Could not detect version of ${webapp_name}" && return 3
+    [ -z "${current_version}" ] && echo " WARNING:(1) Could not detect version of ${webapp_name}" && return 4
 
     (($DEBUG)) && echo " calling helper, check_version_helper ${current_version} >= ${target_version}"
     check_version_helper "${current_version}" ">=" "${target_version}" # note: bug found (needed to quote the operation ">=")
@@ -3778,6 +3797,12 @@ check_app_version() {
     printf "\nSorry, the detected version of ${app_dir##*/} [${current_version}] is older than required minimum version [$2] \n"
     return 1
 }
+
+# arg 1 filter name
+# arg 2 webapp name
+#check_for_filter() {
+#
+#}
 
 #--------------------------------------------------------------------------
 
