--verbose flag and show_type method w/ various cleanup

diff --git a/bin/esg-node b/bin/esg-node
--- a/bin/esg-node
+++ b/bin/esg-node
@@ -271,18 +271,14 @@ check_prerequisites() {
     #----------------------------------------
     echo "Checking requisites... "
 
-    echo -n "Checking for gmake... "
+    ((VERBOSE)) && echo -n "Checking for gmake... "
     gmake --version >& /dev/null
-    [ $? != 0 ] && echo "[FAIL]" && return 1
-    echo "[OK]"
+    ((VERBOSE)) && [ $? != 0 ] && echo "[FAIL]" && return 1
+    ((VERBOSE)) && echo "[OK]"
 
-    echo -n "Checking for X11 libs... "
+    ((VERBOSE)) && echo -n "Checking for X11 libs... "
     Xorg -version >& /dev/null 
-    if [ $? != 0 ]; then
-        echo "[WARNING] X11 is needed for publisher UI..."
-    else
-        echo "[OK]"
-    fi
+    ((VERBOSE)) && ( [ $? != 0 ] && echo "[WARNING] X11 is needed for publisher UI..." || echo "[OK]" )
     #----------------------------------------
 
     echo
@@ -2261,7 +2257,10 @@ test_tds() {
 #####
 # Globus Toolkit ->  MyProxy (client) & GridFTP (server)
 #####
-# Takes arg <selection bit vector> for data-node configuration: ["with-bdm-config"|"bdm-config-only"] see esg-globus script
+# Takes arg <selection bit vector> 
+# The rest of the args are the following...
+# for data-node configuration (GridFTP stuff): ["with-bdm-config"|"bdm-config-only"] see esg-globus script
+# for idp configuration (MyProxy stuff): [gen-self-cert] <dir> | [regen-simpleca] [fetch-certs|gen-self-cert] | ["install"|"update"])
 setup_globus() {
     local sel=${1:-${sel:-0}}
     read_sel
@@ -2369,7 +2368,7 @@ start_globus() {
         pushd ${workdir} >& /dev/null
         source ${scripts_dir}/esg-globus && start_globus_services "${directive}" $@
         data_node_ret=$?
-        [ data_node_ret != 0 ] && echo "Could Not Start Globus Data Node related services (GridFTP)"
+        [ ${data_node_ret} != 0 ] && echo "Could Not Start Globus Data Node related services (GridFTP)"
         popd >& /dev/null
     fi
 
@@ -2383,7 +2382,7 @@ start_globus() {
         pushd ${workdir} >& /dev/null
         source ${scripts_dir}/esg-globus && start_globus_services "${directive}" $@
         idp_node_ret=$?
-        [ idp_node_ret != 0 ] && echo "Could Not Start Globus IDP Node related services (MyProxy)"
+        [ ${idp_node_ret} != 0 ] && echo "Could Not Start Globus IDP Node related services (MyProxy)"
         popd >& /dev/null
     fi
 
@@ -4032,7 +4031,7 @@ show_svc_list() {
     [ $? != 0 ] && echo "(display of node process list limited to root)" && return 0
     echo
     echo "---------------------------"
-    echo -n "Running Node Services... "; ((sel != 0)) && echo "[type code=$sel]" || echo ""
+    echo "Running Node Services... "; ((sel != 0)) && show_type || echo ""
     echo "---------------------------"
     lsof -i |egrep  'postgres|jsvc|globus-gr|java|myproxy'
     echo "---------------------------"
@@ -4054,6 +4053,7 @@ start() {
     [ $((sel & ALL_BIT)) == 0 ] && echo "Cannot Start: No Node Type Specified! (See --help for info on the --type|-t option)  :-|" && exit 1
     
     echo "starting services... ($sel)"
+    /etc/init.d/ntpd start
     
     [ $((sel & ALL_BIT)) != 0 ] && start_postgress
     [ $((sel & ALL_BIT)) != 0 ] && start_tomcat
@@ -4289,6 +4289,13 @@ MAX_BIT=32
 ALL_BIT=$((DATA_BIT+INDEX_BIT+IDP_BIT))
 #---------------
 
+show_type() {
+    [ $((sel & DATA_BIT)) != 0 ] && resolved_to+="data "
+    [ $((sel & INDEX_BIT)) != 0 ] && resolved_to+="index "
+    [ $((sel & IDP_BIT)) != 0 ] && resolved_to+="idp "
+    echo "node type: [ ${resolved_to}] (${sel}) "
+}
+
 main() {
 
     let sel=0
@@ -4345,11 +4352,7 @@ main() {
                 ;;
             --get-type)
                 read_sel
-                local resolved_to=""
-                [ $((sel & DATA_BIT)) != 0 ] && resolved_to+="data "
-                [ $((sel & INDEX_BIT)) != 0 ] && resolved_to+="index "
-                [ $((sel & IDP_BIT)) != 0 ] && resolved_to+="idp "
-                echo "node type: [ ${resolved_to}] (${sel}) "
+                show_type
                 exit 0
                 ;;
             start | --start)
@@ -4426,6 +4429,9 @@ main() {
                 echo "Lawrence Livermore National Laboratory"
                 echo ""
                 exit 0
+                ;;
+            --verbose) 
+                VERBOSE=1
                 ;;
             --clear)
                 self_verify
