esg-node: put the id back in OpenidRelyingParty

diff --git a/bin/esg-node b/bin/esg-node
--- a/bin/esg-node
+++ b/bin/esg-node
@@ -169,9 +169,10 @@ init() {
     node_app_context_root=esg-node
     node_app_home=${tomcat_install_dir}/webapps/${node_app_context_root}
     #NOTE: This is another RedHat/CentOS specific portion!!! it will break on another OS!
-    my_ip_address=$(/sbin/ifconfig | \
-	perl -ple 'print $_ if /inet addr/ and $_ =~ s/.*inet [^:]*:((?:\d+\.){3}\d+).*/$1/g  ;$_=""'\
-    | grep -v ^\s*$ | grep -v 127.0.0.1)
+    my_ip_address=$(ifconfig | grep "inet[^6]" | awk '$0 !~ /127.0.0.1/ { gsub (" *inet [^:]*:",""); print $1}')
+    #my_ip_address=$(/sbin/ifconfig | \
+    #	perl -ple 'print $_ if /inet [^:]*:/ and $_ =~ s/.*inet [^:]*:((?:\d+\.){3}\d+).*/$1/g  ;$_=""'\
+    #| grep -v ^\s*$ | grep -v 127.0.0.1)
     show_summary_latch=0
     source_latch=0
     node_host_ip_address=${my_ip_address}
@@ -982,7 +983,7 @@ stop_tomcat() {
 	echo " WARNING: Unable to stop tomcat, (nicely)" 
 	echo " Hmmm...  okay no more mr nice guy... issuing \"killall jsvc\" and \"pkill -9 $(cat ${tomcat_pid_file})\""
 	killall jsvc
-	pkill -9 $(cat ${tomcat_pid_file}) >& /dev/null
+	kill -9 $(cat ${tomcat_pid_file}) >& /dev/null
 	[ $? != 0 ] && echo "Hmmm... still could not shutdown... process may have already been stopped"
     fi
     /bin/ps -elf | grep jsvc | grep -v grep
@@ -2125,7 +2126,7 @@ done_remark() {
     echo "In order to see if this data node has been installed properly you may direct your browser to:"
     echo "http://${my_ip_address}/${node_app_context_root}"
     echo "http://${my_ip_address}/thredds"
-    echo "http://${my_ip_address}/OpenRelyingParty"
+    echo "http://${my_ip_address}/OpenidRelyingParty"
     echo 
     echo "To see the published test, go your specified gateway: [${ESG_GATEWAY_NAME}]"
     echo "http://${ESG_GATEWAY_SVC_ROOT}"
@@ -2350,7 +2351,7 @@ main() {
 #trap - INT TERM
 
 self_verify 'http://rainbow.llnl.gov/dist' >& /dev/null 
-(( $? > 0 )) && printf "WARNING: $0 could not be verified!! \n(This file, ${0}, has been tampered with)\n\n" && exit 1
+(( $? > 0 )) && printf "WARNING: $0 could not be verified!! \n(This file, ${0}, may have been tampered with or there is a newer version posted at the distribution server.\nPlease re-fetch [esg-update] this script.)\n\n" && exit 1
 
 echo "start time: `date`" >> ${logfile}
 main $@
