script to check for latest

diff --git a/bin/esgf-sh b/bin/esgf-sh
--- a/bin/esgf-sh
+++ b/bin/esgf-sh
@@ -51,6 +51,25 @@ build_jarpath() {
 ############################################
 # Check for server update...
 ############################################
+get_latest() {
+    esg_dist_url=http://198.128.245.140/dist$( ((devel == 1)) && echo "/devel" || echo "")
+    script_install_dir=${install_prefix}/bin
+    mkdir -p ${script_install_dir}
+    pushd $script_install_dir >& /dev/null
+    #Get files
+    local fetch_file=esg-node
+
+    local ret
+    verbose_print "Checking...."
+    checked_get ${esg_dist_url}/esgf-installer/${fetch_file} 
+    ret=$?
+    ((ret == 1)) && echo "ESGF Node Shell script (${fetch_file}) already up-to-date"
+    ((ret == 0)) && echo "Updated ESGF Node Shell script from PCMDI's ESGF distribution site at LLNL"
+    (( ret > 1 )) && popd >& /dev/null && return 1
+    chmod 755 ${fetch_file}
+    popd >& /dev/null
+}
+
 check_for_update() {
     local local_file
     local remote_file
@@ -155,12 +174,13 @@ while [ -n "$1" ]; do
     shift
 done
 
-self_verify
-(( $? > 0 )) && printf "WARNING: $0 could not be verified!! \n(This file, $(readlink -f ${0}), may have been tampered with or there is a newer version posted at the distribution server.\nPlease re-fetch this script.)\n\n" && exit 1
-echo "checking for updates for the ESGF Node Shell"
+#self_verify
+#(( $? > 0 )) && printf "WARNING: $0 could not be verified!! \n(This file, $(readlink -f ${0}), may have been tampered with or there is a newer version posted at the distribution server.\nPlease re-fetch this script.)\n\n" && exit 1
+#echo "checking for updates for the ESGF Node Shell"
 if (($# == 1)) && [ "$1" = "--help" ]; then
     usage
 else
+    #get_latest
     runshell $@
 fi
 
