Fleshing out esgf-sh launch script... (wip)

diff --git a/bin/esgf-sh b/bin/esgf-sh
--- a/bin/esgf-sh
+++ b/bin/esgf-sh
@@ -1,19 +1,140 @@
 #! /bin/bash
 
+DEBUG=${DEBUG:-0}
+VERBOSE=${VERBOSE:-0}
+
 runshell() {
     printf "Welcome, $(whoami) to the ESGF Shell...
 v0.0.1 - by Gavin M. Bell\n\n"
     
-    local my_classpath=""
+    local my_classpath=$(build_classpath ${devel})
     
-    #TODO
-    #Put in code to build the classpath
-    #include the classpath when calling
-    #the shell
-    
-    java esg.common.shell.ESGFShell $@
+    debug_print "java -cp ${my_classpath} esg.common.shell.ESGFShell $@"
+    java -cp ${my_classpath} esg.common.shell.ESGFShell $@
+
     
     echo "Goodbye :-)"
 }
 
-runshell $@
+build_classpath() {
+    local devel=${1:-0}
+}
+
+############################################
+# Check for server update...
+############################################
+check_for_update() {
+    local local_file
+    local remote_file
+    if (( $# == 1 )); then
+        remote_file=${1}
+        local_file=$(readlink -f ${1##*/})
+    elif (( $# == 2 )); then
+        local_file=${1}
+        remote_file=${2}
+    else
+        echo "function \"checked_get\":  Called with incorrect number of args! (fatal)"
+        exit 1
+    fi                      
+    
+    [ ! -e ${local_file} ] && echo " WARNING: Could not find local file ${local_file}" && return 0
+    [ ! -x ${local_file} ] && echo " WARNING: local file ${local_file} not executible" && chmod 755 ${local_file}
+    diff <(md5sum ${local_file} | tr -s " " | cut -d " " -f 1) <(curl -s ${remote_file}.md5 | tr -s " " | cut -d " " -f 1) >& /dev/null
+    (( $? != 0 )) && echo " Update Available @ ${remote_file}" && return 0
+    return 1
+}
+
+checked_get() {
+    check_for_update $@
+    [ $? != 0 ] && return 1
+
+    local local_file
+    local remote_file
+    if (( $# == 1 )); then
+        remote_file=${1}
+        local_file=${1##*/}
+    elif (( $# == 2 )); then
+        local_file=${1}
+        remote_file=${2}
+    else
+        echo "function \"checked_get\":  Called with incorrect number of args! (fatal)"
+        exit 1
+    fi                      
+    
+    if [ -e ${local_file} ]; then
+	cp -v ${local_file} ${local_file}.bak 
+	chmod 600 ${local_file}.bak
+    fi
+    wget -O ${local_file} ${remote_file}
+    [ $? != 0 ] && echo " ERROR: Problem pulling down [${remote_file##*/}] from esg distribution site" && return 2
+    diff <(md5sum ${local_file} | tr -s " " | cut -d " " -f 1) <(curl -s ${remote_file}.md5 | tr -s " " | cut -d " " -f 1) >& /dev/null
+    [ $? != 0 ] && echo " WARNING: Could not verify this file!" && return 3
+    verbose_print "[VERIFIED]"
+    return 0
+}
+
+self_verify() {
+    md5sum /dev/null >& /dev/null
+    [ $? != 0 ] && echo "Could not find program \"md5sum\". Please find program and put it in your path and try again, Sorry :-(" && exit 1
+    #echo "diff <(md5sum ${0} | tr -s " " | cut -d " " -f 1) <(curl ${esg_dist_url}/esgf-installer/${0##*/}.md5 | tr -s " " | cut -d " " -f 1) >& /dev/null "
+    diff <(md5sum ${0} | tr -s " " | cut -d " " -f 1) <(curl -s ${esg_dist_url}/esgf-node-manager/${0##*/}.md5 | tr -s " " | cut -d " " -f 1) >& /dev/null
+    [ $? != 0 ] && return 3
+    verbose_print "[VERIFIED]"
+    return 0
+}
+
+############################################
+# Utils
+############################################
+
+verbose_print() { ((VERBOSE)) && echo $@; return 0; }
+debug_print() { ((DEBUG)) && echo $@; return 0; }
+
+usage() {
+    printf "
+    usage:
+        ${0} [--help]
+    \n"
+    exit 1
+}
+
+############################################
+# Main
+############################################
+
+while [ -n "$1" ]; do 
+    case $1 in 
+	-v | --version)
+	    echo "Earth Systems Grid Federation (http://esgf.org)"
+	    echo "ESGF Node Shell (esgf-sh)"
+	    echo ""
+	    exit 0
+            ;;
+        --verbose)
+            VERBOSE=1;
+            ;;
+        --debug)
+            DEBUG=1;
+            ;;
+        --devel)
+            devel=1;
+            ;;
+        *)
+            echo "unknown switch [$1]"
+            exit 1
+            ;;
+    esac
+    shift
+done
+
+self_verify
+(( $? > 0 )) && printf "WARNING: $0 could not be verified!! \n(This file, $(readlink -f ${0}), may have been tampered with or there is a newer version posted at the distribution server.\nPlease re-fetch this script.)\n\n" && exit 1
+echo "checking for updates for the ESGF Node Shell"
+if (($# == 1)) && [ "$1" = "--help" ]; then
+    usage
+else
+    runshell $@
+fi
+
+#don't source me money grip...
+exit 0
